#!/usr/bin/env python3

import sys, os, subprocess

# 框架约定GOPATH指向src/libs
GOPATH = os.getenv('GOPATH')
if not GOPATH:
    GOPATH = ''
else:
    GOPATH += ':'
PROJECT_HOME = os.path.abspath(os.path.dirname(sys.argv[0]))
GOPATH += PROJECT_HOME + "/:" + PROJECT_HOME + "/libs"
os.environ['GOPATH'] = GOPATH

# 启动编译
code, output = subprocess.getstatusoutput('go build -v -o bin/app')
print(output)
