#!/usr/bin/env python3

import os
import shutil
import subprocess
import sys
import platform
import re

is_cygwin = platform.system().startswith('CYGWIN')
is_windows = is_cygwin or platform.system() == 'Windows'
GOPATH_DELIMITER = ';' if is_windows else ':'


def safepath(str):
    if is_cygwin:
        res = re.compile('/cygdrive/([a-z]{0,2})/(.+)').findall(str)
        if not res:
            print('%s 不是有效的相对windows的目录' % str)
        else:
            str = '%s:/%s' % res[0]
    return str


# 框架约定GOPATH指向src/libs
PROJECT_HOME = safepath(os.path.abspath(os.path.dirname(sys.argv[0])))
GOPATH = GOPATH_DELIMITER.join([
    PROJECT_HOME + '/libs',
    PROJECT_HOME + '/',
])
os.environ['GOPATH'] = GOPATH
os.environ['GO111MODULE'] = 'off'
os.environ['GOPROXY'] = 'https://goproxy.cn'


def install():
    """安装依赖"""
    os.system('go get -v ./')


def merge_packages(src, dst):
    for each in os.listdir(src):
        cur_path = src + '/' + each
        # print(cur_path)
        # 如果不是目录，则跳过
        if not os.path.isdir(cur_path):
            continue
        # 如果是库目录
        if '@' in each:
            dstpkg = dst + '/' + each.split('@')[0]
            #print('移动库 %s to %s' % (cur_path, dstpkg))
            shutil.move(cur_path, dstpkg)
        else:
            # 是模块目录，则需要在dst中创建
            dstdm = dst + '/' + each
            if not os.path.exists(dstdm):
                os.mkdir(dstdm)
                #print('创建域 ' + dstdm)
            merge_packages(cur_path, dstdm)


def install_package_proxy(name):
    print('安装模块 ' + name)

    # 删除mod历史目录
    mod = PROJECT_HOME + '/libs/pkg/mod'
    if os.path.exists(mod):
        shutil.rmtree(mod)

    # 通过代理安装
    os.environ['GO111MODULE'] = 'on'
    os.system('go get -v ' + sys.argv[2])
    os.environ['GO111MODULE'] = 'off'

    # 从mod目录中搬出来
    if os.path.exists(mod + '/cache'):
        shutil.rmtree(mod + '/cache')
    merge_packages(mod, PROJECT_HOME + '/libs/src')

    # 清理
    shutil.rmtree(mod)


def install_package(name):
    """安装模块"""

    # 如果是被屏蔽地址，需要采用代理形式下载
    for each in [
        'google.golang.org'
    ]:
        if each in name:
            install_package_proxy(name)
            return

    print('安装模块 ' + name)
    os.system('go get -v ' + sys.argv[2])

    # 移除get时产生的.git
    rbs = [
        'libs/src/' + sys.argv[2] + '/.git'
    ]
    for rb in rbs:
        if os.path.exists(rb):
            shutil.rmtree(rb)
        else:
            print('%s 不存在' % rb)


def build(debug=False):
    """普通编译"""
    cmds = ['go build -v']
    if debug:
        cmds.append('-gcflags "all=-N -l"')
    cmds.append('-o app')
    exp = ' '.join(cmds)
    # print(exp)
    code, output = subprocess.getstatusoutput(exp)
    print(output)


def debug():
    """启动调试器"""
    exp = 'dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./app -- --debug'
    os.system(exp)


if __name__ == "__main__":
    if 'get' in sys.argv:
        install_package(sys.argv[2])
    elif 'install' in sys.argv:
        install()
    elif 'debug' in sys.argv:
        build(True)
        debug()
    else:
        build()
