#!/usr/bin/env python3

import sys, os, subprocess

# 框架约定GOPATH指向src/libs
GOPATH = os.getenv('GOPATH')
if not GOPATH:
    GOPATH = ''
else:
    GOPATH += ':'
PROJECT_HOME = os.path.abspath(os.path.dirname(sys.argv[0]))
GOPATH += PROJECT_HOME + "/libs:" + PROJECT_HOME + "/"
os.environ['GOPATH'] = GOPATH

# 启动编译
if len(sys.argv) == 1:
    code, output = subprocess.getstatusoutput('go build -v -o bin/app')
    print(output)

# 判断是否时其他功能
if 'get' in sys.argv:
    print('安装模块 ' + sys.argv[2])
    os.system('go get ' + sys.argv[2])
    
